"""final fix

Revision ID: da5570542f86
Revises: 0d7430056922
Create Date: 2026-04-05 00:47:12.096533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da5570542f86'
down_revision = '0d7430056922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('account_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('employee_id', sa.String(length=50), nullable=True))
        batch_op.alter_column('account_holder_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('pin_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.create_unique_constraint(None, ['account_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('pin_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('account_holder_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('employee_id')
        batch_op.drop_column('account_type')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
