name: Banking Core Tests

on:
 push:
  branches: [main]

jobs:
 test:
  runs-on: ubuntu-latest

  env:
   SECRET_KEY: ${{ secrets.SECRET_KEY }}
   ADMIN_KEY: ${{ secrets.ADMIN_KEY }}
  steps:
  - uses: actions/checkout@v3

  - name: Setup Python
    uses: actions/setup-python@v4
    with:
     python-version: 3.11

  - name: Install dependencies
    run: |
     pip install -r requirements.txt
     pip install pytest

  - name: Run Tests
    run: pytest